# ------------------------------------------------------------------------------
# docker-compose.yml
# ------------------------------------------------------------------------------

---

services:

  npx:

    volumes:
      - ./wordpress/:/npm/

  wordpress:

    volumes:
      - &plugin
        "./wordpress/plugin/:\
        /var/www/html/wp-content/plugins/newopera/:ro"
      - &varilink-log-writer-plugin
        "./varilink-plugins/varilink-log-writer/:\
        /var/www/html/wp-content/plugins/varilink-log-writer/:ro"
      - &theme
        "./wordpress/theme/:\
        /var/www/html/wp-content/themes/newopera/"
      - &font
        "./wordpress/theme/node_modules/@fontsource/open-sans/files/:\
        /var/www/html/wp-content/themes/newopera/font/"

  wp-cli:

    volumes:
      - *plugin
      - *theme
      - *font
      - ./backup/:/backup/
